config/routes.rb
Rails.application.routes.draw do
  resources :androids
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get 'androids' => 'androids#index'
  get 'androids/sold_one/:id' => 'androids#sold_one'
end

app/models/android.rb
class Android < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/androids_controller.rb
class AndroidsController < ApplicationController
    before_action :set_android, only: [:show, :edit, :update, :destroy, :sold_one]

  # GET /androids
  # GET /androids.json
  def index
    @androids = Android.all
  end

  # GET /androids/1
  # GET /androids/1.json
  def show
  end

  # GET /androids/new
  def new
    @android = Android.new
  end

  # GET /androids/1/edit
  def edit
  end

  # POST /androids
  # POST /androids.json
  def create
    @android = Android.new(android_params)

    respond_to do |format|
      if @android.save
        format.html { redirect_to @android, notice: 'Android was successfully created.' }
        format.json { render :show, status: :created, location: @android }
      else
        format.html { render :new }
        format.json { render json: @android.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /androids/1
  # PATCH/PUT /androids/1.json
  def update
    respond_to do |format|
      if @android.update(android_params)
        format.html { redirect_to @android, notice: 'Android was successfully updated.' }
        format.json { render :show, status: :ok, location: @android }
      else
        format.html { render :edit }
        format.json { render json: @android.errors, status: :unprocessable_entity }
      end
    end
  end

    def sold_one
        @android = Android.find(params[:id])
        @android.num_of_stock = @android.num_of_stock-1
        @android.save
        redirect_to "/androids/"
    end

  # DELETE /androids/1
  # DELETE /androids/1.json
  def destroy
    @android.destroy
    respond_to do |format|
      format.html { redirect_to androids_url, notice: 'Android was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_android
      @android = Android.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def android_params
      params.require(:android).permit(:name, :brand, :year_released, :camera, :mpixels, :internal_storage, :num_of_sim_slots, :screensize, :operating_system, :num_of_stock)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/androids_helper.rb
module AndroidsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/androids/_form.html.erb
<%= form_with(model: android, local: true) do |form| %>
  <% if android.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(android.errors.count, "error") %> prohibited this android from being saved:</h2>

      <ul>
      <% android.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :year_released %>
    <%= form.text_area :year_released %>
  </div>

  <div class="field">
    <%= form.label :camera %>
    <%= form.text_field :camera %>
  </div>

  <div class="field">
    <%= form.label :mpixels %>
    <%= form.text_field :mpixels %>
  </div>

  <div class="field">
    <%= form.label :internal_storage %>
    <%= form.text_field :internal_storage %>
  </div>

  <div class="field">
    <%= form.label :num_of_sim_slots %>
    <%= form.number_field :num_of_sim_slots %>
  </div>

  <div class="field">
    <%= form.label :screensize %>
    <%= form.text_field :screensize %>
  </div>

  <div class="field">
    <%= form.label :operating_system %>
    <%= form.text_field :operating_system %>
  </div>

  <div class="field">
    <%= form.label :num_of_stock %>
    <%= form.number_field :num_of_stock %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/androids/edit.html.erb
<h1>Editing Android</h1>

<%= render 'form', android: @android %>

<%= link_to 'Show', @android %> |
<%= link_to 'Back', androids_path %>

app/views/androids/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Android nang Bayan Inc.</h1>

<table border = "1">
  <thead>
    <tr>
      <th>Name</th>
      <th>Brand</th>
      <th>Year released</th>
      <th>Camera</th>
      <th>Mpixels</th>
      <th>Internal storage</th>
      <th>Num of sim slots</th>
      <th>Screensize</th>
      <th>Operating system</th>
      <th>Num of stock</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @androids.each do |android| %>
        <% if android.num_of_stock > 0 %>
            <tr>
            <td><%= android.name %></td>
            <td><%= android.brand %></td>
            <td><%= android.year_released %></td>
            <td><%= android.camera %></td>
            <td><%= android.mpixels %></td>
            <td><%= android.internal_storage %></td>
            <td><%= android.num_of_sim_slots %></td>
            <td><%= android.screensize %></td>
            <td><%= android.operating_system %></td>
            <td><%= android.num_of_stock %></td>
            <td><%= link_to 'Show', android %></td>
            <td><%= link_to 'Edit', edit_android_path(android) %></td>
            <td><a href = "http://localhost:3000/androids/sold_one/<%= android.id %>">Sold One</a></td>
            <td><%= link_to 'Destroy', android, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
            </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Android', new_android_path %>

app/views/androids/new.html.erb
<h1>New Android</h1>

<%= render 'form', android: @android %>

<%= link_to 'Back', androids_path %>

app/views/androids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @android.name %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @android.brand %>
</p>

<p>
  <strong>Year released:</strong>
  <%= @android.year_released %>
</p>

<p>
  <strong>Camera:</strong>
  <%= @android.camera %>
</p>

<p>
  <strong>Mpixels:</strong>
  <%= @android.mpixels %>
</p>

<p>
  <strong>Internal storage:</strong>
  <%= @android.internal_storage %>
</p>

<p>
  <strong>Num of sim slots:</strong>
  <%= @android.num_of_sim_slots %>
</p>

<p>
  <strong>Screensize:</strong>
  <%= @android.screensize %>
</p>

<p>
  <strong>Operating system:</strong>
  <%= @android.operating_system %>
</p>

<p>
  <strong>Num of stock:</strong>
  <%= @android.num_of_stock %>
</p>

<%= link_to 'Edit', edit_android_path(@android) %> |
<%= link_to 'Back', androids_path %>

app/views/androids/sold_one.html.erb
<h1>Sold One</h1>

<%= render 'form', android: @android %>

<%= link_to 'Show', @android %> |
<%= link_to 'Back', androids_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AndroidNgBayanInc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>